include ../make.inc

all : pzfft3dv.o fft235.o kernel.o

#kernel.o:
#	$(FC) -c -mp  kernel.f -o kernel.o
#
#pzfft3dv.o:
#	$(FC) -c -mp  pzfft3dv.f -o pzfft3dv.o
#
#fft235.o:
#	$(FC) -c -mp  fft235.f -o fft235.o

clean :
	rm -r -f *.o mpif.h *.lst
