include ../make.inc

OBJ = esm_rgrid_module.o\
      esm_rshell_module.o\
      ps_local_rs_module.o\
      esm_cylindrical_test.o\
      esm_genpot_module.o\
      esm_hartree_module.o\
      esm_kinetic_module.o\

all : $(OBJ)

clean :
	rm -r -f *.o *.mod mpif.h *.lst *.optlog *.i90

