OBJS = hartree_variables.o\
       hartree_sol_1dffte_module.o\
       hartree_sol_ffte_module.o\
       hartree_sol_fftw_module.o\
       hartree_sol_module.o\
       hartree_mol_module.o\
       hartree_ene_module.o\
       hartree_module.o\

